version: "3.7"

networks:
  laravel:

volumes:
  database:

services:
  database:
    image: mysql:latest
    container_name: ${DB_HOST}
    restart: "no"
    volumes:
      - ./docker/database/base.sql:/base.sql
      - database:/var/lib/mysql
    networks:
      - laravel
    ports:
      - ${DB_EXT_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --init-file /base.sql

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/app
    working_dir: /app
    command: composer install

  node:
    image: node:lts
    container_name: node
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn install

  app:
    container_name: app
    restart: "no"
    volumes:
      - ./:/var/www
      - ./docker/app/entrypoint.sh:/entrypoint.sh
    networks:
      - laravel
    depends_on:
      - composer
      - node
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    entrypoint: /entrypoint.sh
    command: php-fpm

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: "no"
    volumes:
      - ./:/var/www
      - ./docker/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    ports:
      - ${WEBSERVER_EXT_PORT}:${WEBSERVER_PORT}
    depends_on:
      - database
      - app
